[package]
name = "gps_data"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ['staticlib']

[build-dependencies]
cbindgen = "0.26.0"

[dependencies]
# c_str_macro = "1.0.3"

